name: AWS-IAC-ADO-Pipeline

trigger:
  branches:
    include:
      - main

variables:
  foldervalue: 'AWS-IAC'
  aws.rolecredential.maxduration: '3600'

stages:
  - stage: ValidateAWSOIDC
    displayName: 'Validate AWS OIDC Authentication'

    jobs:
      - job: ValidateOIDC
        displayName: 'Validate AWS OIDC Connection'

        steps:
          - task: AWSCLI@1
            displayName: 'Validate AWS OIDC Authentication'
            inputs:
              awsCredentials: 'aws-odic'
              regionName: 'ap-south-1'
              awsCommand: 'sts'
              awsSubCommand: 'get-caller-identity'