# This Pipeline uses Accesskeys 
trigger: none

pool:
  vmImage: ubuntu-latest
variables:
- group: aws-terraform-secrets

stages:

- stage: Destroy

  jobs:

  - deployment: TerraformDestroy

    environment: Production

    strategy:

      runOnce:

        deploy:

          steps:

          - checkout: self

          - task: DownloadSecureFile@1
            name: tfvars
            inputs:
              secureFile: terraform.tfvars

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: latest

          - script: |
              terraform init

              terraform destroy --auto-approve \
                -var-file=$(tfvars.secureFilePath)
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

            displayName: Terraform Destroy